version: '3'

services:
  web:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    command: sh -c "poetry run uvicorn oauth_auth.main:app --port 8000 --reload"
    volumes:
      - .:/app